[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project]
name = "automation-module-akamai"
version = "1.0.2"
description = ""
requires-python = ">=3.10,<3.12"
dynamic = ["dependencies"]

[tool.poetry]
package-mode = false

[tool.black]
line-length = 119
target-version = ["py310"]
include = "\\.pyi?$"

[tool.isort]
profile = "black"
line_length = 119

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
sekoia-automation-sdk = "^1.18.3"
edgegrid-python = "^2.0.0"
orjson = "^3.10.16"
requests-ratelimiter = "^0.7.0"
requests = "^2.32.3"
cachetools = "^5.5.2"
structlog = "^25.2.0"
pydantic = ">=2.10,<3.0"
prometheus-client = ">=0.21.0,<0.22.0"
urllib3 = ">=2,<3"

[tool.coverage.run]
omit = ["tests/*", "main.py"]

[tool.poetry.group.dev.dependencies]
pytest = "*"
pytest-cov = "*"
requests = "*"
requests-mock = "*"
freezegun = "^1.5.1"
