name: Test with uv
description: Test an automation module with uv project manager

inputs:
  module:
    description: "The module to test"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@6ee6290f1cbc4156c0bdd66691b2c144ef8df19a # v7.4.0
      with:
        enable-cache: true
        activate-environment: true

    - name: Install Dependencies
      id: install-dependencies
      shell: bash
      run: |
        uv sync --frozen
      working-directory: ${{ inputs.module }}

    - name: Execute Ruff lint
      shell: bash
      run: |
        uv run ruff check .
      working-directory: ${{ inputs.module }}

    - name: Execute Ruff format check
      shell: bash
      run: |
        uv run ruff format --check .
      working-directory: ${{ inputs.module }}

    - name: Execute Mypy
      shell: bash
      run: |
        uv run mypy .
      working-directory: ${{ inputs.module }}

    - name: Execute Python tests
      id: execute-tests
      shell: bash
      run: |
        uv run pytest --junit-xml=junit.xml --cov-report term --cov-report xml:coverage.xml --cov . --cov-config pyproject.toml
      working-directory: ${{ inputs.module }}
