[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[project]
name = "automation-module-darktrace"
version = "0.0"
description = ""
authors = []
requires-python = ">=3.11,<3.15"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "sekoia-automation-sdk>=1.24.0,<2",
    "structlog>=26.1.0,<27",
    "urllib3>=2.7.0,<3",
]

[dependency-groups]
dev = [
    "pytest",
    "pytest-cov",
    "requests",
    "requests-mock",
    "black",
    "isort",
    "mypy",
    "ruff"
]

[tool.uv]
package = false

[tool.black]
line-length = 119
target-version = ["py38"]
include = "\\.pyi?$"

[tool.isort]
profile = "black"
line_length = 119

[tool.coverage.run]
omit = ["tests/*", "main.py"]
