import pytest


@pytest.fixture
def misp_base_url():
    yield "http://fake.url/"


@pytest.fixture
def misp_base_server(misp_base_url: str, requests_mock):
    requests_mock.get(misp_base_url + "servers/getPyMISPVersion.json", json={"version": "2.4.62"})
    requests_mock.get(
        misp_base_url + "servers/getVersion",
        json={
            "version": "2.4.142",
            "perm_sync": True,
            "perm_sighting": True,
            "perm_galaxy_editor": True,
            "request_encoding": ["gzip"],
        },
    )
    requests_mock.get(
        misp_base_url + "users/view/me",
        json={
            "User": {
                "id": "2",
                "password": "*****",
                "org_id": "1",
                "email": "admin@sekoia.io",
                "autoalert": True,
                "invited_by": "1",
                "gpgkey": "",
                "certif_public": "",
                "nids_sid": "6100818",
                "termsaccepted": True,
                "newsread": "1679326201",
                "role_id": "1",
                "change_pw": False,
                "contactalert": True,
                "disabled": False,
                "expiration": None,
                "current_login": "1679433722",
                "last_login": "1679388064",
                "force_logout": False,
                "date_created": "1664737175",
                "date_modified": "1679326201",
                "sub": None,
                "external_auth_required": False,
                "external_auth_key": None,
                "last_api_access": "0",
            },
            "Role": {
                "id": "1",
                "name": "admin",
                "created": "2022-10-02 18:57:18",
                "modified": "2022-10-02 18:57:18",
                "perm_add": True,
                "perm_modify": True,
                "perm_modify_org": True,
                "perm_publish": True,
                "perm_delegate": True,
                "perm_sync": True,
                "perm_admin": True,
                "perm_audit": True,
                "perm_auth": True,
                "perm_site_admin": True,
                "perm_regexp_access": True,
                "perm_tagger": True,
                "perm_template": True,
                "perm_sharing_group": True,
                "perm_tag_editor": True,
                "perm_sighting": True,
                "perm_object_template": True,
                "default_role": False,
                "memory_limit": "",
                "max_execution_time": "",
                "restricted_to_site_admin": False,
                "perm_publish_zmq": True,
                "perm_publish_kafka": True,
                "perm_decaying": True,
                "enforce_rate_limit": False,
                "rate_limit_count": "0",
                "perm_galaxy_editor": True,
                "perm_warninglist": False,
                "permission": "3",
                "permission_description": "publish",
            },
            "UserSetting": [],
            "Organisation": {
                "id": "1",
                "name": "ORGNAME",
                "date_created": "2022-10-02 18:57:50",
                "date_modified": "2022-10-02 18:57:50",
                "description": "Automatically generated admin organisation",
                "type": "ADMIN",
                "nationality": "",
                "sector": "",
                "created_by": "0",
                "uuid": "5a1c18e9-b05b-420c-815c-6f883e6fef77",
                "contacts": None,
                "local": True,
                "restricted_to_domain": None,
                "landingpage": None,
            },
        },
    )

    yield requests_mock


@pytest.fixture
def misp_event():
    """Real MISP event to make sure tests are as accurate as possible"""
    return {
        "Event": {
            "id": "47433",
            "orgc_id": "175",
            "org_id": "4",
            "date": "2019-06-19",
            "threat_level_id": "3",
            "info": "Daily Incremental Cryptolaemus Emotet IOCs (payload)",
            "published": True,
            "uuid": "5d09b3bd-50e4-48c8-9e20-05dd0df8e8c7",
            "attribute_count": "10",
            "analysis": "2",
            "timestamp": "1560916925",
            "distribution": "3",
            "proposal_email_lock": False,
            "locked": True,
            "publish_timestamp": "1560917027",
            "sharing_group_id": "0",
            "disable_correlation": False,
            "extends_uuid": "",
            "Org": {
                "id": "4",
                "name": "InThreat",
                "uuid": "5697b91d-2090-441f-b153-75e895ca48b7",
            },
            "Orgc": {
                "id": "175",
                "name": "CERT-BUND_495",
                "uuid": "56a64d7a-63dc-4471-bce9-4accc25ed029",
            },
            "Attribute": [
                {
                    "id": "1184795",
                    "type": "sha256",
                    "category": "Payload delivery",
                    "to_ids": True,
                    "uuid": "039ece6f-22ee-40da-a23d-a7042df3e873",
                    "event_id": "47433",
                    "distribution": "5",
                    "timestamp": "1560916925",
                    "comment": "Daily Cryptolaemus Import (Emotet IoCs for 2019-06-18 observed by Palo Alto Networks.)",  # noqa: E501
                    "sharing_group_id": "0",
                    "deleted": False,
                    "disable_correlation": False,
                    "object_id": "0",
                    "object_relation": None,
                    "value": "7603ff14295c93bc1b73c6c0d74148c555337fb52b4104752ce0d2f5f6f2940d",
                    "Galaxy": [],
                    "ShadowAttribute": [],
                },
                {
                    "id": "1184796",
                    "type": "sha256",
                    "category": "Payload delivery",
                    "to_ids": True,
                    "uuid": "4ed3facc-1f71-4109-9663-c63d56326a5d",
                    "event_id": "47433",
                    "distribution": "5",
                    "timestamp": "1560916925",
                    "comment": "Daily Cryptolaemus Import (Emotet IoCs for 2019-06-18 observed by Palo Alto Networks.)",  # noqa: E501
                    "sharing_group_id": "0",
                    "deleted": False,
                    "disable_correlation": False,
                    "object_id": "0",
                    "object_relation": None,
                    "value": "5e08d513e3402640b4492c481f588877a33be51c68dc20f65eda2396232f1dc0",
                    "Galaxy": [],
                    "ShadowAttribute": [],
                },
                {
                    "id": "1184797",
                    "type": "sha256",
                    "category": "Payload delivery",
                    "to_ids": True,
                    "uuid": "80760cd5-3650-45a3-9bf6-52299901e69a",
                    "event_id": "47433",
                    "distribution": "5",
                    "timestamp": "1560916925",
                    "comment": "Daily Cryptolaemus Import (Emotet IoCs for 2019-06-18 observed by Palo Alto Networks.)",  # noqa: E501
                    "sharing_group_id": "0",
                    "deleted": False,
                    "disable_correlation": False,
                    "object_id": "0",
                    "object_relation": None,
                    "value": "9f17da6a8d15ef891e7a18cfeecfd6ce2dfa17b3086df3e7e11b2009486c23c3",
                    "Galaxy": [],
                    "ShadowAttribute": [],
                },
                {
                    "id": "1184798",
                    "type": "sha256",
                    "category": "Payload delivery",
                    "to_ids": True,
                    "uuid": "5f76b788-972d-45f1-a6fe-308c8b92b9c1",
                    "event_id": "47433",
                    "distribution": "5",
                    "timestamp": "1560916925",
                    "comment": "Daily Cryptolaemus Import (Emotet IoCs for 2019-06-18 observed by Palo Alto Networks.)",  # noqa: E501
                    "sharing_group_id": "0",
                    "deleted": False,
                    "disable_correlation": False,
                    "object_id": "0",
                    "object_relation": None,
                    "value": "76c3a81789b8673e39c2e17b6cd04c8707016322dd1b6aee0278d8b0c3c1c36e",
                    "Galaxy": [],
                    "ShadowAttribute": [],
                },
                {
                    "id": "1184799",
                    "type": "sha256",
                    "category": "Payload delivery",
                    "to_ids": True,
                    "uuid": "a9408145-3d39-447e-b1ec-11d6f37d43d2",
                    "event_id": "47433",
                    "distribution": "5",
                    "timestamp": "1560916925",
                    "comment": "Daily Cryptolaemus Import (Emotet IoCs for 2019-06-18 observed by Palo Alto Networks.)",  # noqa: E501
                    "sharing_group_id": "0",
                    "deleted": False,
                    "disable_correlation": False,
                    "object_id": "0",
                    "object_relation": None,
                    "value": "d4a74735785dfbfd340064e834462258f9016097da8aa9f92f5fc843e2d22b34",
                    "Galaxy": [],
                    "ShadowAttribute": [],
                },
                {
                    "id": "1184800",
                    "type": "sha256",
                    "category": "Payload delivery",
                    "to_ids": True,
                    "uuid": "4cbb34e3-18cc-4841-911a-b310c1f32e13",
                    "event_id": "47433",
                    "distribution": "5",
                    "timestamp": "1560916925",
                    "comment": "Daily Cryptolaemus Import (Emotet IoCs for 2019-06-18 observed by Palo Alto Networks.)",  # noqa: E501
                    "sharing_group_id": "0",
                    "deleted": False,
                    "disable_correlation": False,
                    "object_id": "0",
                    "object_relation": None,
                    "value": "a9645b9208c4b75b51dee6cc02844342fe7aba184b1055cc0fcccd30e641be95",
                    "Galaxy": [],
                    "ShadowAttribute": [],
                },
                {
                    "id": "1184801",
                    "type": "sha256",
                    "category": "Payload delivery",
                    "to_ids": True,
                    "uuid": "45be802f-e5fa-469d-82b3-cacdb39a14d6",
                    "event_id": "47433",
                    "distribution": "5",
                    "timestamp": "1560916925",
                    "comment": "Daily Cryptolaemus Import (Emotet IoCs for 2019-06-18 observed by Palo Alto Networks.)",  # noqa: E501
                    "sharing_group_id": "0",
                    "deleted": False,
                    "disable_correlation": False,
                    "object_id": "0",
                    "object_relation": None,
                    "value": "396587e0e59d771f3f90d601fe8230201d7e9497dcf482344f531ecbb9d6da84",
                    "Galaxy": [],
                    "ShadowAttribute": [],
                },
                {
                    "id": "1184802",
                    "type": "sha256",
                    "category": "Payload delivery",
                    "to_ids": True,
                    "uuid": "216b63a4-1296-4a52-9a61-09bd098654d3",
                    "event_id": "47433",
                    "distribution": "5",
                    "timestamp": "1560916925",
                    "comment": "Daily Cryptolaemus Import (Emotet IoCs for 2019-06-18 observed by Palo Alto Networks.)",  # noqa: E501
                    "sharing_group_id": "0",
                    "deleted": False,
                    "disable_correlation": False,
                    "object_id": "0",
                    "object_relation": None,
                    "value": "f47dad9e1c6bf06287993b129adea90fed9347262b4e7060a5bfeb0fd1da2a03",
                    "Galaxy": [],
                    "ShadowAttribute": [],
                },
                {
                    "id": "1184803",
                    "type": "sha256",
                    "category": "Payload delivery",
                    "to_ids": True,
                    "uuid": "139e8907-9e1b-4177-bfd7-e6701e02554c",
                    "event_id": "47433",
                    "distribution": "5",
                    "timestamp": "1560916925",
                    "comment": "Daily Cryptolaemus Import (Emotet IoCs for 2019-06-18 observed by Palo Alto Networks.)",  # noqa: E501
                    "sharing_group_id": "0",
                    "deleted": False,
                    "disable_correlation": False,
                    "object_id": "0",
                    "object_relation": None,
                    "value": "7cf5151c21e271989e6702405537e51ec6c7e097de943cfe1428f6f0cfed3cd9",
                    "Galaxy": [],
                    "ShadowAttribute": [],
                },
                {
                    "id": "1184804",
                    "type": "sha256",
                    "category": "Payload delivery",
                    "to_ids": True,
                    "uuid": "5973b9f5-8110-40f8-a7c2-b80c6eff5953",
                    "event_id": "47433",
                    "distribution": "5",
                    "timestamp": "1560744125",
                    "comment": "Daily Cryptolaemus Import (Emotet IoCs for 2019-06-18 observed by Palo Alto Networks.)",  # noqa: E501
                    "sharing_group_id": "0",
                    "deleted": False,
                    "disable_correlation": False,
                    "object_id": "0",
                    "object_relation": None,
                    "value": "1bdaa4b98aee67b7e3e46802b871671b38e632a87e316c22ac272a6bd5b8e282",
                    "Galaxy": [],
                    "ShadowAttribute": [],
                },
                {
                    "id": "1114896",
                    "type": "text",
                    "category": "External analysis",
                    "to_ids": False,
                    "uuid": "5cf9f232-b714-462b-84a0-17a9c0a80108",
                    "event_id": "47433",
                    "distribution": "5",
                    "timestamp": "1560744125",
                    "comment": "",
                    "sharing_group_id": "0",
                    "deleted": False,
                    "disable_correlation": False,
                    "object_id": "0",
                    "object_relation": None,
                    "value": "some analysis",
                    "Galaxy": [],
                    "ShadowAttribute": [],
                },
            ],
            "ShadowAttribute": [],
            "RelatedEvent": [],
            "Galaxy": [],
            "Object": [],
            "Tag": [
                {
                    "id": "5",
                    "name": "tlp:white",
                    "colour": "#ffffff",
                    "exportable": True,
                    "hide_tag": False,
                    "user_id": "0",
                    "numerical_value": None,
                },
                {
                    "id": "157",
                    "name": 'misp-galaxy:tool="Emotet"',
                    "colour": "#0088cc",
                    "exportable": True,
                    "hide_tag": False,
                    "user_id": "0",
                    "numerical_value": None,
                },
            ],
        }
    }
