[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "Automation module for MISP"
description = ""
version = "0.0"
authors = []
package-mode = false

[tool.black]
line-length = 119
target-version = ["py38"]

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
pymisp = "^2.4.200"
sekoia-automation-sdk = "^1.18.0"
stix2 = "^3.0.1"
cachetools = "^5.5.0"
orjson = "^3.10.12"
requests = "^2.32.3"

[tool.poetry.group.dev.dependencies]
pytest = "*"
pytest-cov = "*"
requests-mock = "*"
freezegun = "*"

[tool.coverage.run]
omit = ["tests/*", "main.py"]