[tool.poetry]
name = "Automation Module for The Hive"
description = ""
version = "0.0"
authors = []
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
sekoia-automation-sdk = "1.13.0"
thehive4py = "2.0.0b5"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-cov = "*"
requests-mock = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 119
target-version = ['py39']
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 119

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra --junit-xml=junit.xml --cov-report term --cov-report xml:coverage.xml --cov=thehive"
testpaths = ["tests"]

[tool.coverage.run]
omit = [
    "tests/*",
    "main.py",
]