import os

CLIENT_WAIT_FOR_RESULT_TIMEOUT_DEFAULT = int(os.environ.get("ELASTIC_WAIT_FOR_RESULT_TIMEOUT_DEFAULT", 60))
CLIENT_WAIT_FOR_RESULT_TIMEOUT_MAX = int(os.environ.get("ELASTIC_WAIT_FOR_RESULT_TIMEOUT_MAX", 600))
