[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "Automation module for Nutanix Prism"
version = "0.0"
description = "Automation module assets and helpers for Nutanix Prism integration"
authors = []
package-mode = false

[tool.black]
line-length = 119
target-version = ["py311"]
include = "\\.pyi?$"

[tool.isort]
profile = "black"
line_length = 119

[tool.ruff]
target-version = "py311"
line-length = 119
fix = true

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
sekoia-automation-sdk = "^1.22.1"
requests = "*"
orjson = "*"
structlog = "*"

[tool.poetry.group.dev.dependencies]
pytest = "*"
pytest-cov = "*"
requests-mock = "*"
freezegun = "^1.5.1"

