[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[project]
name = "sekoiaio"
version = "2.76.0"
description = ""
authors = []
requires-python = ">=3.14,<3.15"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "requests",
    "sekoia-automation-sdk>=1.26.0,<2",
    "kafka-python",
    "tenacity",
    "ujson",
    "websocket-client",
    "gevent",
    "orjson",
    "structlog>=25.5.0,<26",
    "smart-open>=7.5.0,<8",
    "black>=26.1.0,<27",
]

[dependency-groups]
dev = [
    "pytest",
    "pytest-cov",
    "requests",
    "requests-mock",
]

[tool.uv]
package = false

[tool.uv.build-backend]
module-root = ""

[tool.ruff]
target-version = "py314"
line-length = 119
fix = true

[tool.coverage.run]
omit = ["tests/*", "main.py"]
