name: get_api_v1_accounts_accountId_securityevents_type_export_period
pipeline:
- name: http
- name: output
stages:
  http:
    kind: http
    properties:
      method: GET
      url: '{{inputs.base_url}}/api/v1/accounts/{{inputs.accountId}}/securityevents/{{inputs.type}}/export/{{inputs.period}}'
      auth:
        bearer:
          token: '{{inputs.token}}'
          scheme: Bearer
      headers:
        WatchGuard-API-Key: '{{apikey}}'
      params:
        hostname: '{{inputs.hostname}}'
        top: '{{inputs.top}}'
        skip: '{{inputs.skip}}'
    asserts:
      error_400:
        predicate: '{{response.status_code != 400}}'
        fail: BAD REQUEST.
      error_403:
        predicate: '{{response.status_code != 403}}'
        fail: ACCESS DENIED.
      error_404:
        predicate: '{{response.status_code != 404}}'
        fail: NOT FOUND.
      error_405:
        predicate: '{{response.status_code != 405}}'
        fail: METHOD NOT ALLOWED.
      error_500:
        predicate: '{{response.status_code != 500}}'
        fail: INTERNAL ERROR.
      success:
        predicate: '{{response.status_code == 200}}'
        fail: Expected a successful (2xx) status code, got {{response.status_code}}
    captures:
      result: '{{response.json}}'
  output:
    kind: output
    properties:
      result: '{{http.result}}'
description: Retrieves a list of security events of the specified type for the specified
  device. The response to this request is limited to 3,000 records.
inputs:
  type:
    type: integer
    description: Type of configuration to return. Currently, only 2-Workstations and
      servers or 3-Android are supported types for this operation.
  hostname:
    type: string
    description: Host name (base-64 encoded) of the device you want to retrieve security
      events for.
  accountId:
    type: string
    description: Your WatchGuard Cloud account ID.
  period:
    type: integer
    description: 'Period of time you want to retrieve.

      - 1: Last 24 hours

      - 7: Last 7 days

      - 30: Last 30 days

      '
  base_url:
    type: string
    description: Base URL for the API
    enum:
    - https://api.usa.cloud.watchguard.com/rest/endpoint-security/management
    - https://api.deu.cloud.watchguard.com/rest/endpoint-security/management
    - https://api.jpn.cloud.watchguard.com/rest/endpoint-security/management
  skip:
    type: integer
    description: Bypasses the specified number of objects in the results returned.
  token:
    type: string
    description: The bearer token for authentication
    default: '{{token}}'
  top:
    type: integer
    description: Specifies the number of objects to retrieve (there is a maximum supported
      by the server).
