name: get_api_v1_accounts_accountId_installers
pipeline:
- name: http
- name: output
stages:
  http:
    kind: http
    properties:
      method: GET
      url: '{{inputs.base_url}}/api/v1/accounts/{{inputs.accountId}}/installers'
      auth:
        bearer:
          token: '{{inputs.token}}'
          scheme: Bearer
      headers:
        WatchGuard-API-Key: '{{apikey}}'
      params:
        platformId: '{{inputs.platformId}}'
        managedConfigurationId: '{{inputs.managedConfigurationId}}'
        useActiveDirectory: '{{inputs.useActiveDirectory}}'
    asserts:
      error_400:
        predicate: '{{response.status_code != 400}}'
        fail: BAD REQUEST.
      error_403:
        predicate: '{{response.status_code != 403}}'
        fail: ACCESS DENIED.
      error_404:
        predicate: '{{response.status_code != 404}}'
        fail: NOT FOUND.
      error_405:
        predicate: '{{response.status_code != 405}}'
        fail: METHOD NOT ALLOWED.
      error_500:
        predicate: '{{response.status_code != 500}}'
        fail: INTERNAL ERROR.
      success:
        predicate: '{{response.status_code == 200}}'
        fail: Expected a successful (2xx) status code, got {{response.status_code}}
    captures:
      result: '{{response.json}}'
  output:
    kind: output
    properties:
      result: '{{http.result}}'
description: Retrieves the URL to download an installation package that installs Panda
  software with the specified managed configuration settings on a device.
inputs:
  platformId:
    type: integer
    description: "Identifier of the platform you want to retrieve the installation\
      \ package URL for.\n- 1: Windows\n- 2: Linux\n- 3: macOS\n- 4: Android\n- 5:\
      \ iOS                \n"
  useActiveDirectory:
    type: boolean
    description: Indicates whether to integrate the device into Active Directory.
  accountId:
    type: string
    description: Your WatchGuard Cloud account ID.
  base_url:
    type: string
    description: Base URL for the API
    enum:
    - https://api.usa.cloud.watchguard.com/rest/endpoint-security/management
    - https://api.deu.cloud.watchguard.com/rest/endpoint-security/management
    - https://api.jpn.cloud.watchguard.com/rest/endpoint-security/management
  managedConfigurationId:
    type: string
    description: Identifier of the managed configuration you want to retrieve the
      installation package URL for.
  token:
    type: string
    description: The bearer token for authentication
    default: '{{token}}'
