[project]
name = "sekoia-automation-utils"
version = "0.0"
description = ""
authors = []
requires-python = ">=3.14,<3.15"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "sekoia-automation-sdk>=1.26.0,<2",
    "jsonpath_ng>=1.5,<2",
    "orjson",
    "lxml",
    "structlog>=25.5.0",
]

[dependency-groups]
dev = [
    "pytest",
    "pytest-cov",
    "requests-mock",
]

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false

[tool.coverage.run]
omit = ["tests/*", "main.py"]

[tool.ruff]
line-length = 119
target-version = "py314"

[tool.ruff.lint]
select = ["A", "ARG", "E", "F", "I", "N", "RUF", "UP", "W"]
