name: viewHostNames
pipeline:
- name: http
- name: output
stages:
  http:
    kind: http
    properties:
      method: GET
      url: '{{inputs.base_url}}/v2/hosts/{{inputs.ip}}/names'
      auth:
        basic:
          username: '{{inputs.username}}'
          password: '{{inputs.password}}'
      params:
        per_page: '{{inputs.per_page}}'
        cursor: '{{inputs.cursor}}'
    asserts:
      error_401:
        predicate: '{{response.status_code != 401}}'
        fail: You must authenticate with a valid API ID and secret.
      error_429:
        predicate: '{{response.status_code != 429}}'
        fail: Too many requests.
      success:
        predicate: '{{response.status_code == 200}}'
        fail: Expected a successful (2xx) status code, got {{response.status_code}}
    captures:
      result: '{{response.json}}'
  output:
    kind: output
    properties:
      result: '{{http.result}}'
description: Fetches a list of host names for the specified IP address.
inputs:
  per_page:
    type: integer
    description: The maximum number of hits to return in each response (minimum of
      1, maximum of 100).
  ip:
    type: string
    description: The IP Address of the requested host.
  password:
    type: string
    description: The password for basic authentication
    default: '{{password}}'
  base_url:
    type: string
    description: Base URL for the API
    enum:
    - https://search.censys.io/api
  cursor:
    type: string
    description: Cursor token from the API response, which fetches the next or previous
      page of hits when added to the endpoint URL.
  username:
    type: string
    description: The username for basic authentication
    default: '{{username}}'
