name: viewResult
pipeline:
- name: http
- name: output
stages:
  http:
    kind: http
    properties:
      method: GET
      url: '{{inputs.base_url}}/v1/data/{{inputs.series}}/{{inputs.result}}'
      auth:
        basic:
          username: '{{inputs.username}}'
          password: '{{inputs.password}}'
    asserts:
      error_404:
        predicate: '{{response.status_code != 404}}'
        fail: The requested series or result does not exist.
      error_429:
        predicate: '{{response.status_code != 429}}'
        fail: Your query was not executed because you have exceeded your specified
          rate limit.
      error_500:
        predicate: '{{response.status_code != 500}}'
        fail: An unexpected error occurred when trying to execute your query. Try
          again at a later time or contact us at [support@censys.io](mailto:support@censys.io)
          if the problem persists.
      success:
        predicate: '{{response.status_code == 200}}'
        fail: Expected a successful (2xx) status code, got {{response.status_code}}
    captures:
      result: '{{response.json}}'
  output:
    kind: output
    properties:
      result: '{{http.result}}'
description: "> The Censys legacy v1 API contains API endpoints which are being maintained\
  \ until replacement v2 endpoints are available. \n\nThe View Result endpoint returns\
  \ data on a particular scan (result), as found in the Get Series or View Series\
  \ endpoints."
inputs:
  series:
    type: string
    description: The ID of the series.
  result:
    type: string
    description: The ID of the result.
  password:
    type: string
    description: The password for basic authentication
    default: '{{password}}'
  base_url:
    type: string
    description: Base URL for the API
    enum:
    - https://search.censys.io/api
  username:
    type: string
    description: The username for basic authentication
    default: '{{username}}'
