name: getCommentByHost
pipeline:
- name: http
- name: output
stages:
  http:
    kind: http
    properties:
      method: GET
      url: '{{inputs.base_url}}/v2/hosts/{{inputs.ip}}/comments/{{inputs.comment_id}}'
      auth:
        basic:
          username: '{{inputs.username}}'
          password: '{{inputs.password}}'
    asserts:
      error_404:
        predicate: '{{response.status_code != 404}}'
        fail: Not Found
      error_422:
        predicate: '{{response.status_code != 422}}'
        fail: Unprocessable Entity
      success:
        predicate: '{{response.status_code == 200}}'
        fail: Expected a successful (2xx) status code, got {{response.status_code}}
    captures:
      result: '{{response.json}}'
  output:
    kind: output
    properties:
      result: '{{http.result}}'
description: 'Returns a specific comment on the given host.

  '
inputs:
  ip:
    type: string
    description: The IP Address of the requested host.
  password:
    type: string
    description: The password for basic authentication
    default: '{{password}}'
  base_url:
    type: string
    description: Base URL for the API
    enum:
    - https://search.censys.io/api
  comment_id:
    type: string
    description: The ID of the requested comment.
  username:
    type: string
    description: The username for basic authentication
    default: '{{username}}'
