[build-system]
requires = ["uv_build>=0.11.21,<0.12.0"]
build-backend = "uv_build"

[project]
name = "automation-module-github"
version = "0.0"
description = ""
authors = []
requires-python = ">=3.11,<3.15"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "sekoia-automation-sdk>=1.24.0,<2",
    "structlog>=25.5.0,<26",
    "orjson>=3.11.8,<4",
    "aiohttp<3.14",  # new version doesn't play along with aioresponses
    "aiolimiter>=1.2.1,<2",
    "jwt>=1.4.0,<2",
]

[dependency-groups]
dev = [
    "pytest",
    "pytest-cov",
    "pytest-asyncio",
    "pytest-xdist",
    "pytest-env",
    "Faker",
    "isort",
    "mypy",
    "black[colorama]",
    "ruff",
    "aioresponses",
    "requests",
    "requests-mock"
]

[tool.uv]
package = false
default-groups = "all"

[tool.mypy]
strict = true
ignore_missing_imports = true
allow_subclassing_any = true
allow_untyped_calls = true
pretty = true
show_error_codes = true
implicit_reexport = true
allow_untyped_decorators = true
warn_return_any = true
exclude = ["tests/*"]

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests"]
filterwarnings = [
  "error",
  "ignore::DeprecationWarning",
  "ignore:.*unclosed.*:ResourceWarning",
]
addopts = '''
  --strict-markers
  --tb=short
  --asyncio-mode=auto
  --cov=github_modules
  --cov-branch
  --cache-clear
  --cov-report=html
  --cov-report=term-missing:skip-covered
  --cov-fail-under=90
'''

[tool.coverage.run]
omit = ["tests/*", "main.py", "github_modules/metrics.py"]
