[project]
name = "automation-module-harfanglab"
version = "0.0"
description = ""
authors = []
requires-python = ">=3.14,<4"
dependencies = [
    "sekoia-automation-sdk>=1.23.1,<2",
    "pydantic>=2.10,<3",
    "requests",
    "requests-ratelimiter>=0.7.0,<1",
    "stix2-patterns>=2.0.0,<3",
    "structlog>=24.4.0,<25",
    "findpython>=0.7.0,<1",
    "aiolimiter>=1.2.1,<2",
]

[dependency-groups]
dev = [
    "pytest>=7.0",
    "pytest-cov",
    "requests-mock",
    "types-requests",
    "aiohttp>=3.12.14,<4",
]
lint = [
    "ruff>=0.14",
    "mypy",
]

[tool.uv]
package = false
default-groups = ["dev", "lint"]

[tool.ruff]
line-length = 119
target-version = "py314"
fix = true

[tool.ruff.lint]
select = ["A", "ARG", "E", "F", "I", "N", "RUF", "UP", "W"]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["ARG"]

[tool.mypy]
python_version = "3.14"
install_types = true
non_interactive = true
ignore_missing_imports = true
show_column_numbers = true
exclude = ["tests/"]
plugins = ["pydantic.mypy"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = """
    --cache-clear
    --cov=harfanglab
    --cov-report=term-missing:skip-covered
    -ra
"""
testpaths = ["tests"]
filterwarnings = [
  "error",
  "ignore::DeprecationWarning",
  "ignore:.*unclosed.*:ResourceWarning",
]

[tool.coverage.run]
omit = ["tests/*", "main.py"]
