name: uploadVectraMatchRules
pipeline:
- name: http
- name: output
stages:
  http:
    kind: http
    properties:
      method: POST
      url: '{{inputs.base_url}}/vectra-match/rules'
      auth:
        oauth2:
          token_url: https://{{inputs.vectra_portal_url}}/oauth2/token
          client_credentials:
            client_id: '{{inputs.client_id}}'
            client_secret: '{{inputs.client_secret}}'
          scopes: []
    asserts:
      success:
        predicate: '{{response.status_code == 201}}'
        fail: Expected a successful (2xx) status code, got {{response.status_code}}
  output:
    kind: output
    properties:
      result: '{{http.result}}'
inputs:
  client_id:
    type: string
    description: The client ID for OAuth2 client credentials flow
    default: '{{client_id}}'
  client_secret:
    type: string
    description: The client secret for OAuth2 client credentials flow
    default: '{{client_secret}}'
  base_url:
    type: string
    description: Base URL for the API
    enum:
    - https://{{inputs.vectra_portal_url}}/api/v3.3
  vectra_portal_url:
    type: string
    default: platform.vectra.ai
